[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
position = "before"
times = 1
pattern = "G.FUNCS.continue_unlock = function()"
payload = '''
local __typist_exit_overlay_menu_impl = G.FUNCS.exit_overlay_menu
G.FUNCS.exit_overlay_menu = function()
  __typist_exit_overlay_menu_impl()
  require("typist.mod.settings-page").draw_layout_change_notification()
end
'''
match_indent = false

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
position = "before"
times = 1
pattern = "function create_UIBox_settings()"
payload = '''
local __typist_create_UIBox_options_impl = create_UIBox_options
create_UIBox_options = function()
  return require("typist.mod.settings-page").insert_settings_page_button(__typist_create_UIBox_options_impl())
end
'''
match_indent = false
